apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }} 
  name: {{ .Values.app.name }}-{{ .Values.app.function }}-secret
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.function }}-secret
type: Opaque
data:
 # echo -n "4xSvTVrbJjV3GsqkhTLs" | base64
 
  # OPC MVP space
  # OPCUSERNAME: bXdwX3VzZXI= # mwp_user
  # OPCPASSWORD: NHhTdlRWcmJKalYzR3Nxa2hUTHM= # 4xSvTVrbJjV3GsqkhTLs
  # OPC GlobalPV space
  OPCUSERNAME: bQ== # m
  OPCPASSWORD: bQ== # m
  # OPC for testing env
  # OPCUSERNAME: dXNlcg== # user
  # OPCPASSWORD: dXNlcg== # user
  RABBITMQUSERNAME: Z3Vlc3Q= # guest
  RABBITMQPASSWORD: Z3Vlc3Q= # guest