apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opc-processdata-read
  namespace: flux-system
spec:
  interval: 30s
  chart:
    spec:
      chart: opc-client # bo folder charts/opc-client
      version: '0.1.0'
      sourceRef:
        # kind: HelmRepository
        kind: GitRepository
        name: opc-client
        namespace: flux-system
      # interval: 10m
  # values:
  #   replicaCount: 2