apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: opc-processdata-read
  namespace: opc-client
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/marolo2/opcua-client-helm