---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: opc-client
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/marolo2/opcua-client-helm/
  ref:
    branch: main
  secretRef:
    name: github-token

# ---

# API pochodzi z toolkit

# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: opc-client
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: opc-client
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: opc-client
  
