---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opc-client
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/marolo2/opcua-client-helm/opcua-client
