deployment:
  image: ghcr.io/marolo2/opcuaclient # "marolo2/opc-processdata-read"
  tag: 1.0.4
  pullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
app:
  name: "opc-processdata-marcin01" # "opc-processdata"
  function: "read"
namespace: "opc-client"
opc:
  opcHost: "opc.tcp://10.0.0.83" # "opc.tcp://192.168.196.1"  "opc.tcp://192.168.0.104" 
  opcPort: 4840
  opcSubperiod: 100 # in miliseconds
rabbitmq:
  rabbitmqHost: "rabbitmq-0.rabbitmq.rabbitmq-instance.svc.cluster.local"
  rabbitmqPort: "5672"
  exchangeName: "PubProcessDataOPC_Exchange"
  exchangeType: "direct"
  routingKey: "PubProcessDataOPC_Key"
  queueName: "AgregateProcessDataOPC"
  clientName: "PubProcessDataOPC"

# tag info:
#
# ver. 1.0.0 - odczyt danych asynchroniczny (na event) z OPC UA
#
# ver. 1.0.1 - dodane w client RabbitMQ config dla wiadomosci
#              delivery_mode=pika.DeliveryMode.Persistent
